---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "react"
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"