---
template:
  - "@streetname, she's a @quirk11 @metatype @archetype from @geo who @quirk21."
  - "@streetname, she's an @quirk12 @metatype @archetype from @geo who @quirk21."
  - "@streetname, he's a @quirk11 @metatype @archetype from @geo who @quirk22."
  - "@streetname, he's an @quirk12 @metatype @archetype from @geo who @quirk22."
  
streetname:
  - "Poison"
  - "Carbon"
  - "Midnight"
  - "Sarge"
  - "Silver"
  - "Midnight Sun"
  - "Grace"
  - "Runt"
  - "Dagger"
  - "Nova"
  - "Enigma"
  - "Owl"
  - "Sekhmet"
  - "Plague"
  - "Rat"
  - "Nuke"
  - "Razor"
  - "Shark"
  - "Hatchet"
  - "Tiger"
  - "Zero-Cool"
  - "Gibson"
  - "Bishop"
  - "Prince"
  - "Hunter"
  - "Swiftshot"
  - "Edge"
  - "Silence"
  - "Tear"
  - "Ripper"
  - "Deadeye"
  - "Scythe"
  - "Addict"
  - "Astral Claw"
  - "Chrome"
  - "Rapid-fire"
  - "Squid"
  - "Grim"
  - "Cauldron"
  - "Curse"
  - "Titan"
  - "Giant"
  - "Freak"
  - "Acid"
  - "Rain"
  - "Skulker"
  - "Animal"
  - "Bullseye"
  - "Blizzard"
  - "Crow"
  - "Spider"
  - "Talon"
  - "Tyrant"
  - "Raptor"
  - "Cutthroat"
  - "Tarantula"
  - "Hotshot"
  - "Guardian"
  - "Kodiak"
  - "Shockwave"
  - "Centurion"
  - "Mongrel"
  - "Dynamo"
  - "Dynamite"
  - "Ace"
  - "Autumn"
  - "Cobra"
  - "Flash"
  - "Neon"
  - "Mercy"
  - "Arbalest"
  - "Bullet"
  - "Demon"
  - "Squeamish"
  - "Doc"
  - "Grizzly"
  - "Critias"

metatype:
  - "Dwarf"
  - "Human"
  - "Troll"
  - "Elf"
  - "Ork"

archetype:
  - "Street Samurai"
  - "Decker"
  - "Face"
  - "Mage"
  - "ex-Cop"
  - "Medic"
  - "Gutter Punk"
  - "Occult Investigator"
  - "Adept"
  - "Gunslinger Adept"
  - "Smuggler"
  - "Rigger"
  - "Tech"
  - "Rocker"
  - "Reporter"
  - "Street Shaman"
  - "Edgerunner"
  - "Fixer"
  - "Cat Burglar"
  - "Extraction Expert"
  - "ex-Bodyguard"
  - "Social Chameleon"
  - "Combat Mage"
  - "Street Mage"
  - "Otaku"
  - "Mercenary"
  - "Sprawl Ganger"
  - "Data Thief"
  - "Fence"
  - "Go-Ganger"
  - "Gumshoe"
  - "Negotiator"
  - "Weapons Specialist"
  - "Vigilante"
  - "Hit Mage"
  - "Technoshaman"
  - "Idol"
  - "Burnout"

geo:
  - "the UCAS"
  - "the CAS"
  - "the ADL"
  - "Japan"
  - "CalFree"
  - "Denver"
  - "the Sioux Nation"
  - "the UTE Nation"
  - "the Pueblo Council"
  - "Atzlan"
  - "the UK"
  - "France"
  - "China"
  - "Vladivostok"
  - "the Barrens"
  - "Pomoria"
  - "the SOX"
  - "Australia"
  - "Tir Tairngire"
  - "Tir na Nog"
  - "Amazonia"
  - "Chicago"
  - "Rhine-Ruhr"
  - "London"
  - "Berlin"
  - "Paris"
  - "New York"
  - "Hong Kong"
  - "Tokyo"
  - "Russia"
  - "Seattle"

quirk11:
  - "paranoid"
  - "delusional"
  - "spaced-out"
  - "drug-hating"
  - "skittish"
  - "book obsessed"
  - "music loving"
  - "bookish"
  - "joke cracking"
  - "morally bankrupt"
  - "stoner"
  - "stuck-in-the-past"
  - "lab raised"
  - "wise-ass"
  - "methodical"
  - "hot-headed"
  - "cursed"
  - "bigoted"
  - "tactless"
  - "sarcastic"
  - "serious"
  - "talented"
  - "guarded"
  - "headstrong"
  - "short-tempered"
  - "broke"
  - "haunted"
  - "tiny"
  - "well-behaved"
  - "squeamish"
  - "respected"
  - "brilliant"
  - "capable"
  - "calm"
  - "clever"
  - "confident"
  - "cultured"
  - "cheerful"
  - "friendly"
  - "fun-loving"
  - "charismatic"
  - "honorable"
  - "gentle"
  - "modest"
  - "pessimistic"
  - "proud"
  - "quiet"

quirk12:
  - "ex-con"
  - "ex-corp"
  - "eccentric"
  - "on-the-run"
  - "ice-cold"
  - "anarchist"
  - "augmented"
  - "awakened"
  - "ambitious"
  - "easy going"
  - "aristocratic"
  - "accident prone"
  - "energetic"
  - "overconfident"
  - "irresponsible"
  - "irritating"
  - "adaptable"
  - "efficient"
  - "intelligent"
  - "innovative"
  - "organized"
  - "optimistic"
  - "urbane"
  - "upright"
  - "unambitious"
  - "uninhibited"

quirk21:
  - "carries a large coin which she is always rolling over her knuckles"
  - "can uncannily tell if someone is telling a lie or the truth"
  - "is always trying to recruit people to join the Universal Brotherhood"
  - "corrects people when they use colloquial speech when she's nervous"
  - "is constantly checking her wristphone"
  - "has a grudge against Ares"
  - "always offers her teammates hot coffee"
  - "has a history with the Vory"
  - "is a total pro, but would kill her own mother for a real-meat steak"
  - "is indebted to the Yaks"
  - "is afraid of the sewers"
  - "survived a Ghoul hunt as a child"
  - "likes to meditate during lulls in the action"
  - "left her old live behind because of a secret shame"
  - "has a weird fixation with dragons"
  - "is constantly humming off-key pop songs"
  - "is cybered far beyond any reasonable limits"
  - "is uneasy around magic"
  - "is looking for her stolen memories"
  - "takes every chance to hurt the corps"
  - "constantly drops out-of-context quotes by famous philosophers"
  - "might only have a year left to live"
  - "takes every chance to steal secret culinary recipes"
  - "has ties to a mystic order"
  - "is obsessed with visiting the Astral Planes"
  - "lost a secret bet against a dragon"
  - "never closes her eyes"
  - "thinks that grunting and shrugging count as polite conversation"
  - "doesn't believe in magic"
  - "once crashed a Mafia wedding"
  - "obsessively cleans her weapons and tools"
  - "is constantly striving to prove her worth"
  - "likes to taunt security forces"
  - "curses like a particularly angry sailor"
  - "is always polite to the elderly"
  - "thinks that anti-virus softs are for people who don't know what they're doing"
  - "is afraid of the Matrix"
  - "is afraid of the Deep Resonance"
  - "is afraid of Cyberware"
  - "is afraid of Bioware"
  - "is afraid of the Augmented"
  - "can't stand still for even a moment"
  - "is a Metahuman Rights Activist"
  - "just can't stop flirting"
  - "doesn't notice that she's always flirting"
  - "has pet-names for all her weapons"
  - "smokes enough to contribute to the air-pollution warning levels"
  - "distrusts men"
  - "distrusts women"
  - "has a drinking problem"
  - "takes naps at the most inappropiate moments"
  - "has a grudge against Saeder-Krupp"
  - "has a grudge against Renraku"
  - "has a grudge against Mitsuhama"
  - "has a grudge against Shiawase"
  - "has a grudge against Doc Wagon"
  - "has a grudge against Aztech"
  - "distrusts Humans"
  - "distrusts Elves"
  - "distrusts Orks"
  - "distrusts Dwarves"
  - "distrusts Trolls"
  - "is looking for salvation"
  - "is somehow hated by Watcher spirits"
  - "believes in some weird conspiracy theories"
  - "can speak Sperethiel, but dislikes doing so"
  - "gets a slight nervous tic whenenver she enters a Stuffer Shack's food section"
  - "likes to set things on fire"
  - "programmed her virtual assistant to look, and act, like a penguin"
  - "owns a cat she'll defend with her life"
  - "is interested in the mythical history of the world"
  - "carries a book wherever she goes"
  - "at times forgets non-critical mission details"
  - "is owed a favour by the Triads"
  - "is hunted by Saeder-Krupp"
  - "is hunted by Renraku"
  - "is hunted by Mitsuhama"
  - "is hunted by Shiawase"
  - "is hunted by Aztech"
  - "is hunted by the Mafia"
  - "is hunted by the Yakuza"
  - "is hunted by the Triads"
  - "is hunted by the Vory"
  - "is hunted by a Dragon"
  - "excessively uses initials or acronyms and doesn't bother to explain them"
  - "takes stupid bets for small amounts of money while on runs"
  - "always says 'Can't get any worse...' at exactly the wrong moments"
  - "tries to catch every Episode of 'Wyrm Talk'"
  - "seems to always have sunflower seeds at hand"
  - "once shot at someone, because they told a bad joke"
  - "was once a Shadowrunner, but then took a bullet to the knee"
  - "is owed a favour by the Mafia"
  - "is owed a favour by the Yakuza"
  - "is owed a favour by Ares"
  - "is owed a favour by DocWagon"
  - "is owed a favour by Saeder-Krupp"
  - "is owed a favour by Renraku"
  - "is owed a favour by Shiawase"
  - "is owed a favour by Mitsuhama"
  - "is owed a favour by Aztech"
  - "is owed a favour by a Dragon"

quirk22:
  - "carries a large coin which he is always rolling over his knuckles"
  - "can uncannily tell if someone is telling a lie or the truth"
  - "is always trying to recruit people to join the Universal Brotherhood"
  - "corrects people when they use colloquial speech when he's nervous"
  - "is constantly checking his wristphone"
  - "has a grudge against Ares"
  - "always offers his teammates hot coffee"
  - "has a history with the Vory"
  - "is a total pro, but would kill his own mother for a real-meat steak"
  - "is indebted to the Yaks"
  - "is afraid of the sewers"
  - "survived a Ghoul hunt as a child"
  - "likes to meditate during lulls in the action"
  - "left his old live behind because of a secret shame"
  - "has a weird fixation with dragons"
  - "is constantly humming off-key pop songs"
  - "is cybered far beyond any reasonable limits"
  - "is uneasy around magic"
  - "is looking for his stolen memories"
  - "takes every chance to hurt the corps"
  - "constantly drops out-of-context quotes by famous philosophers"
  - "might only have a year left to live"
  - "takes every chance to steal secret culinary recipes"
  - "has ties to a mystic order"
  - "is obsessed with visiting the Astral Planes"
  - "lost a secret bet against a dragon"
  - "never closes his eyes"
  - "thinks that grunting and shrugging count as polite conversation"
  - "doesn' believe in magic"
  - "once crashed a Mafia wedding"
  - "obsessively cleans his weapons and tools"
  - "is constantly striving to prove his worth"
  - "likes to taunt security forces"
  - "curses like a particularly angry sailor"
  - "is always polite to the elderly"
  - "thinks that anti-virus softs are for people who don't know what they're doing"
  - "is afraid of the Matrix"
  - "is afraid of the Deep Resonance"
  - "is afraid of Cyberware"
  - "is afraid of Bioware"
  - "is afraid of the Augmented"
  - "can't stand still for even a moment"
  - "is a Metahuman Rights Activist"
  - "just can't stop flirting"
  - "doesn't notice that he's always flirting"
  - "has pet-names for all his weapons"
  - "smokes enough to contribute to the air-pollution warning levels"
  - "distrusts women"
  - "distrusts men"
  - "has a drinking problem"
  - "takes naps at the most inappropiate moments"
  - "has a grudge against Saeder-Krupp"
  - "has a grudge against Renraku"
  - "has a grudge against Mitsuhama"
  - "has a grudge against Shiawase"
  - "has a grudge against Doc Wagon"
  - "has a grudge against Aztech"
  - "distrusts Humans"
  - "distrusts Elves"
  - "distrusts Orks"
  - "distrusts Dwarves"
  - "distrusts Trolls"
  - "is looking for salvation"
  - "is somehow hated by Watcher spirits"
  - "believes in some weird conspiracy theories"
  - "can speak Sperethiel, but dislikes doing so"
  - "gets a slight nervous tic whenenver he enters a Stuffer Shack's food section"
  - "likes to set things on fire"
  - "programmed his virtual assistant to look, and act, like a penguin"
  - "owns a cat he'll defend with his life"
  - "is interested in the mythical history of the world"
  - "carries a book wherever he goes"
  - "at times forgets non-critical mission details"
  - "is owed a favour by the Triads"
  - "is hunted by Saeder-Krupp"
  - "is hunted by Renraku"
  - "is hunted by Mitsuhama"
  - "is hunted by Shiawase"
  - "is hunted by Aztech"
  - "is hunted by the Mafia"
  - "is hunted by the Yakuza"
  - "is hunted by the Triads"
  - "is hunted by the Vory"
  - "is hunted by a Dragon"
  - "excessively uses initials or acronyms and doesn't bother to explain them"
  - "takes stupid bets for small amounts of money while on runs"
  - "always says 'Can't get any worse...' at exactly the wrong moments"
  - "tries to catch every Episode of 'Wyrm Talk'"
  - "seems to always have sunflower seeds at hand"
  - "once shot at someone, because they told a bad joke"
  - "was once a Shadowrunner, but then took a bullet to the knee"
  - "is owed a favour by the Mafia"
  - "is owed a favour by the Yakuza"
  - "is owed a favour by Ares"
  - "is owed a favour by DocWagon"
  - "is owed a favour by Saeder-Krupp"
  - "is owed a favour by Renraku"
  - "is owed a favour by Shiawase"
  - "is owed a favour by Mitsuhama"
  - "is owed a favour by Aztech"
  - "is owed a favour by a Dragon"